# Run common script to get hosts ready
- hosts: all
  roles:
      - common

# Configure plex, sonarr, and all other tools
- hosts: plex2
  roles:
      - plex
      - sonarr
      - plexpy
      - radarr
      - mono
      - rclone
      - plex-drive
      - encfs
      - ombi
      - unionfs-fuse
      - { role: nginx, nginx_servers: "{{ nginx_sites }}" }
      - { role: nzbget, nzbget_mount_path: "{{ mount_path }}" }
      - { role: encfs-mount, encfs_mount_path: "{{ mount_path }}"}
      - { role: plex-drive-mount, plex_mount_path: "{{ mount_path }}"}
      - { role: unionfs-fuse-mount, union_mount_path: "{{ mount_path }}"}
      - cron

