- name: plex-drive-service
  template:
      src: plex-drive.service.j2
      dest: /etc/systemd/system/plex-drive.service
      owner: root
      group: root
      mode: 0755

- name: create acd-storage
  file:
      path: "{{ plex_mount_path }}/.gdrive-storage"
      state: directory

- name: create .acd-storage
  file:
      path: "{{ plex_mount_path }}/.gdrive-storage"
      state: directory

- name: create local-storage
  file:
      path: "{{ plex_mount_path }}/local-storage"
      state: directory

- name: create .local-storage
  file:
      path: "{{ plex_mount_path }}/.local-storage"
      state: directory

- meta: flush_handlers

- name: ensure plex-drive enabled and started
  systemd:
      name: plex-drive
      enabled: yes
  ignore_errors: "{{ ansible_check_mode }}" 
  notify:
      - restart plex-drive
