- group: name=radarr state=present
- name: add user radarr
  user:
      name: radarr
      group: radarr
      shell: /bin/bash
      move_home: yes
      home: /home/radarr
      createhome: yes


- name: radarr extract
  unarchive:
      src: https://github.com/Radarr/Radarr/releases/download/v0.2.0.375/Radarr.develop.0.2.0.375.linux.tar.gz
      dest: /opt/Radarr
      remote_src: True

- file: dest=/opt/Radarr owner=radarr group=radarr recurse=yes


- name: systemd radarr
  template:
      src: radarr.service.j2
      dest: /etc/systemd/system/radarr.service
      owner: root
      group: root
      mode: 0640

- meta: flush_handlers

- name: ensure radarr enabled and started
  systemd:
      name: radarr
      enabled: yes
      state: started
  ignore_errors: "{{ ansible_check_mode }}" 
  notify:
      - restart radarr

 
