- group: name=sonarr state=present
- name: add user sonarr
  user:
      name: sonarr
      group: sonarr
      shell: /bin/bash
      move_home: yes
      home: /home/sonarr
      createhome: yes


- name: add apt key 
  apt_key:
      keyserver: keyserver.ubuntu.com
      id: FDA5DFFC

- name: add apt repository 
  apt_repository:
      repo: deb https://apt.sonarr.tv/ master main 
      update_cache: yes

- name: install nzbdrone
  apt:
      pkg: nzbdrone
      state: present
  ignore_errors: "{{ ansible_check_mode }}" 

- name: systemd sonarr
  template:
      src: sonarr.service.j2
      dest: /etc/systemd/system/sonarr.service
      owner: root
      group: root
      mode: 0640

- meta: flush_handlers

- name: ensure sonarr enabled and started
  systemd:
      name: sonarr
      enabled: yes
      state: started
  ignore_errors: "{{ ansible_check_mode }}" 
  notify:
      - restart sonarr

 
