- name: add apt key 
  apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

- name: add apt repository 
  apt_repository:
      repo: deb http://download.mono-project.com/repo/debian wheezy main
      update_cache: yes

- name: install mono
  apt:
      pkg: mono-complete
      state: present
  ignore_errors: "{{ ansible_check_mode }}" 
