- name: unionfsmount
  template:
      src: unionfs-mount.j2
      dest: /usr/bin/unionfsmount
      owner: root
      group: root
      mode: 0755

- name: create sorted dir
  file:
      path: "{{ union_mount_path }}/sorted"
      state: directory

- name: add sorted union fstab entry
  mount:
      name: "{{ union_mount_path }}/sorted"
      src: "unionfsmount#{{ union_mount_path }}/gdrive=RO:{{ union_mount_path }}/local-storage=RW"
      fstype: fuse
      opts: rw,user,auto,umask=0000
      state: present

