- group: name=couch state=present
- name: add user couch
  user:
      name: couch
      group: couch
      shell: /bin/bash
      move_home: yes
      home: /opt/couch
      createhome: yes

- git: repo=https://github.com/CouchPotato/CouchPotatoServer.git dest=/opt/couch/CouchPotatoServer

- name: systemd couchpotato
  template:
      src: couchpotato.service.j2
      dest: /etc/systemd/system/couchpotato.service
      owner: root
      group: root
      mode: 0640

- meta: flush_handlers

- name: ensure CouchPotato enabled and started
  systemd:
      name: couchpotato
      enabled: yes
      state: started
  ignore_errors: "{{ ansible_check_mode }}" 
  notify:
      - restart couch
