- name: add apt key
  apt_key:
      url: https://downloads.plex.tv/plex-keys/PlexSign.key

- name: add apt repository
  apt_repository:
        repo:  deb https://downloads.plex.tv/repo/deb/ public main
        update_cache: yes

- name: install plex
  apt:
      pkg: plexmediaserver
      state: present
  ignore_errors: "{{ ansible_check_mode }}"

- name: systemd plex
  template:
      src: plexmediaserver.service.j2
      dest: /etc/systemd/system/plexmediaserver.service
      owner: root
      group: root
      mode: 0640

- meta: flush_handlers

- name: just force systemd to reread configs (2.4 and above)
  systemd: daemon_reload=yes

- name: ensure plex enabled and started
  systemd:
      name: plexmediaserver
      enabled: True
      state: started
  ignore_errors: "{{ ansible_check_mode }}"
  notify:
      - restart plex


